### ISSUE TITLE
这个项目会更新到完成吗？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [laojianzi/mdclubgo#19]
mdclub还比较喜欢  比较想用go版本的  会更新到能正常使用吗？

**Comment by Yakumo-Yukari** [comment]
我以为大佬会选择 主流的 gin或者iris框架呢 看了下使用的echo

**Comment by laojianzi** [comment]
@Yakumo-Yukari 会持续更新，希望后续也有精力可以在开源上

为什么选择 Echo，因为项目本身的目的是学习，我会按照 [Go 开发者路线图](https://github.com/Alikhll/golang-developer-roadmap) 上推荐的技术栈来进行，一开始使用 fiber，但后期发现太新了，有些需要用上的能力/行为暂时还没有，所以后面就换了 Echo

感谢你的关注 😄
